# Generated by Django 5.0.2 on 2024-02-16 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0002_ingredients'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredients',
            old_name='expiry_date',
            new_name='Date',
        ),
    ]
